pentoo/pentoo-overlay

- sys-fs/ext4-crypt/ext4-crypt-9999.ebuild
"Linux kernel 4.1 introduced native encryption for the ext4 filesystem. 
This is a userspace tool to manage encrypted ext4 directories", 
info: http://blog.quarkslab.com/a-glimpse-of-ext4-filesystem-level-encryption.html 
github: https://github.com/gdelugre/ext4-crypt 
regards
> ext4-crypt ebuild

- net-analyzer/nikto/nikto-2.1.5-r3.ebuild
Just found nikto can not run, and with this error:
```
- Could not find a valid nikto config file
```
The default config file is /etc/nikto.conf, but in this ebuild it installed to /etc/nikto/nikto.conf.
> net-analyzer/nikto: fix config file could not find error.

- net-analyzer/nessus-bin/nessus-bin-6.5.3-r1.ebuild
Fix QA_PREBUILT variable, remove unused X USE, remove non existent i386 rpm, add pax-marks to the appropriate binaries and update the quickstart instructions for nessus, remove old unused ssl symlinks.
> Nessus fixes

- app-crypt/oclhashcat/oclhashcat-3.0.0_pre20160610.ebuild
This builds and installs fine for me, now that a couple of small
Makefile tweaks have been merged upstream.
Note, even though 3.0 is still in beta, I do not recommend trying an
ebuild for the 2.0x release sources.  The build environment in 3.0 has
improved hugely; ebuilds for building 2.0 from source are far more
painful.
> Added an ebuild for the current oclhashcat beta.

- app-crypt/oclhashcat/oclhashcat-3.0.0.ebuild
After 3.0.0 there was one commit that removed "this is a beta" warnings from various docs; this points at that commit rather than the release tagged commit.
> Update to the 3.0.0 release (plus one cleanup).

- sys-fs/ext4-crypt/ext4-crypt-9999.ebuild
upstream gdelugre/ext4-crypt replaced libscrypt by libsodium since Sep 25, 2016
> Changed libscrypt dependency to libsodium for ext4-crypt

- dev-util/unicorn/unicorn-1.0.1.ebuild
I am running a stock (actually hardened) Gentoo setup w/ the Pentoo overlay added later; I did not use the Pentoo installer. I also haven't enabled the pentoo profile. This might be why I'm seeing issues other users aren't.
Unicorn comes with an included version of QEMU, and it's build breaks when Python 3 is used. This patch forces it to build w/ Python 2 and adds a build dependency.
Speaking of which, I noticed that in this package the run-time dependencies include pkg-config, and the build dependencies include glib. Is that a typo? Should we swap them?
> unicorn: force building internal qemu w/ python 2

- net-proxy/mitmproxy/mitmproxy-1.0.2-r1.ebuild
- net-proxy/mitmproxy/mitmproxy-2.0.2.ebuild
- net-proxy/mitmproxy/mitmproxy-9999.ebuild
- net-wireless/wifi-pumpkin/wifi-pumpkin-0.8.4.ebuild
- net-wireless/wifi-pumpkin/wifi-pumpkin-0.8.5.ebuild
- profiles/pentoo/base/package.accept_keywords/dev-python
- profiles/updates/3Q-2017
Since `dev-python/hyper-h2` has been in-tree for a while now, we should migrate stuff to that ebuild. This pull request puts in an update for the move and fixes dependencies for `net-proxy/mitmproxy` and `net-wireless/wifi-pumpkin`.
> h2: remove package in favor of in-tree ebuild

- dev-python/kaitaistruct/kaitaistruct-0.6.ebuild
- dev-python/kaitaistruct/kaitaistruct-0.7.ebuild
The Python package `kaitaistruct` is *not* the parser generator. In mitmproxy, the parser is already generated and this package provides the runtime library the generated parser requires. Additionally, the preferred notation for `SRC_URI` for PyPI is `mirror://pypi/${PN:0:1}/${PN}/${P}.tar.gz`. I updated the description to distinguish the package and updated the source uri.
Let me know if you would like for me to change anything else or have any questions.
Thanks for all of your work!
> kaitaistruct: fix description and use preferred notation for SRC_URI

- dev-ruby/parseconfig/parseconfig-1.0.8.ebuild
I'm not sure where you got that homepage and license, but this PR fixes those. Also, there are no distributed tests in the gem so we should indicate that.
Thanks for all of your work!
> parseconfig: fix homepage, license, and lack of tests

- dev-util/unicorn/unicorn-1.0.1-r1.ebuild
unicorn was failing emerge's multilib-strict check (after compile; before install) on my system, which means it was trying to put files into /usr/lib instead of /usr/lib32 or /usr/lib64.
> unicorn: fix multilib issue on install

- dev-util/unicorn/unicorn-1.0.1-r2.ebuild
I "properly" fixed a hack I had done a few months ago, according to blshkv's advice: https://github.com/pentoo/pentoo-overlay/pull/187. I tested it and it builds properly even when the system python is 3.4.
Also, I added static libs; I don't see why these were not included in the first place since they're built by default w/ Unicorn.
Trying to squash PR's together now to not create overload. Although I do have one more major one coming for unicorn and unicorn-bindings, so I'll let that one wait.
> unicorn: two tiny changes

- dev-util/unicorn/unicorn-1.0.1-r2.ebuild
- profiles/pentoo/arch/amd64/make.defaults
I went for static-libs, as this seems to be targeted at packages which install static libs alongside shared libs, which is what is happening here (see https://github.com/pentoo/pentoo-overlay/pull/231).
> unicorn: add static-libs use flag

- profiles/pentoo/arch/amd64/make.defaults
I am really sorry for all the little commits, and now literally reverting a revert commit. Turns out the issue that I initially reverted 1982f3b8ded54e3849c07dc64f4519de423b12cb was caused by ccache being misconfigured on my machine, _not_ something that should affect other users.
Looking at the logs it looks like ZeroChaos is having some trouble today too, hah ;)
Let me know if you'd rather have me pile up changes into larger patches before submitting PR's.
> Revert "Revert "unicorn: add arm and aarch64 to base profile""

- dev-util/unicorn/unicorn-1.0.1-r3.ebuild
The unicorn-bindings package has some problems: first the ebuild breaks when trying to install some of the non-Python bindings (which no packages in Pentoo depend on anyway), and second, installing the unicorn-bindings packages causes the entire Unicorn shared library to be rebuild, except that this build does not respect UNICORN_TARGETS. So as a fix, I simply added a python use flag to the unicorn ebuild, which will install the python bindings during the install. This avoids rebuilding all of Unicorn. If this is acceptable, we could potentially move forward w/ unicorn-bindings[python] being a simple wrapper for unicorn[python], if it's needed for backward-compatability.
> unicorn: add python bindings

- app-crypt/johntheripper/johntheripper-9999.ebuild
This is the -9999 ebuild I've been using in my overlay. CUDA support has been removed for a while now so I took that out of the ebuild. I also took out the minimal use flag, but I can restructure this and add that back in if you feel it is necessary.
Any comments/does this look good?
> johntheripper: add -9999 ebuild

- dev-python/python-ntlm/python-ntlm-1.1.0-r1.ebuild
This package needs a proper description as well as a fix where the correct flag for examples is USE=examples (https://packages.gentoo.org/useflags/examples).
> python-ntlm: fix description, use flags, and dependencies

- profiles/pentoo/base/package.accept_keywords/media-libs
On amd64 hardened, after pentoo-installer from 2018 rc7.1, portage is synced.
When trying to update world with:
> emerge --deep --update --newuse world -vta
this is one of the errors:
> !!! The following update has been skipped due to unsatisfied dependencies:
> 
> net-wireless/gnuradio:0
> 
>   selected: (net-wireless/gnuradio-3.7.11-r3:0/3.7.11::gentoo, ebuild scheduled for merge)
>   skipped: (net-wireless/gnuradio-3.7.13.3-r1:0/3.7.13.3::gentoo, ebuild scheduled for merge) (see unsatisfied dependency below)
> 
> !!! All ebuilds that could satisfy ">=media-libs/codec2-0.8.1" have been masked.
> !!! One of the following masked packages is required to complete your request:
> - media-libs/codec2-0.8.1::gentoo (masked by: ~amd64 keyword)
> 
> (dependency required by …
> accept_keywords: gnuradio needs codec2

- profiles/pentoo/base/package.accept_keywords/app-emulation
On amd64 hardened, after pentoo-installer from 2018 rc7.1, portage is synced.
When trying to update world with:
> emerge --deep --update --newuse world -vta
this is one of the errors:
> app-emulation/open-vm-tools:0
> 
>   selected: (app-emulation/open-vm-tools-10.1.15:0/0::gentoo, installed)
>   skipped: (app-emulation/open-vm-tools-10.2.5:0/0::gentoo, ebuild scheduled for merge) (see unsatisfied dependency below)
> 
> !!! All ebuilds that could satisfy "dev-libs/xml-security-c" have been masked.
> !!! One of the following masked packages is required to complete your request:
> - dev-libs/xml-security-c-1.7.3::gentoo (masked by: ~amd64 keyword)
> 
> (dependency required by "app-emulation/open-vm-tools-10.2.5::gentoo[vgauth,xml-security-c]" [ebuild])
> For more information, see the MASKED …
> accept_keywords: open-vm-tools needs xml-security-c

- profiles/pentoo/base/package.accept_keywords/dev-qt
qt 5.9.6 is stable in Gentoo, but causes blocked packages in Pentoo. The
reason is dev-qt/qtcharts, all other qt 5.9.6 packages, that we use, are stable in
Gentoo.
Updated accept_packages/dev-qt: Update version of qtcharts, remove all
other packages because they are stable in Gentoo.
Tested on 2018 rc 7.2
> Update qt to 5.9.6: Change accept_keywords

- pentoo/pentoo-system/files/pentoo.conf
Fix for FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/pentoo/pentoo.asc'
> Fix pentoo.conf: use pentoo-keyring.asc

- app-crypt/yubioath-desktop/yubioath-desktop-4.3.4-r1.ebuild
Package currently fails to build. Change happened upstream 1 year ago:
https://github.com/Yubico/yubioath-desktop/commit/2add28eb317b1dff909fd7691e81d6e8f0dc7881
Only change is the line:
> domenu resources/yubioath-desktop.desktop
> app-crypt/yubioath-desktop: rename .desktop file

- app-crypt/cryptohaze-combined/cryptohaze-combined-1.31.ebuild
- app-crypt/cryptohaze-combined/cryptohaze-combined-9999.ebuild
- dev-util/collabreate/collabreate-0.4.0_p20140528.ebuild
'svn.sourceforge.net' is no longer available, the svn repos are now in:
https://svn.code.sf.net/p/...
This PR fixes the 2 packages that used 'svn.sourceforge.net.
> Move sourceforge svn repos

- dev-util/unicorn/unicorn-1.0.1-r5.ebuild
r4 failed to build with:
ERROR: Cannot use 'python', Python 2.4 or later is required.
Note that Python 3 or later is not yet supported.
Use --python=/path/to/python to specify a supported Python.
Fixes: make.sh in src_compile() did not forward those variables
@blshkv : this builds, r4 does not, that's all I know, merge or not at your will
> dev-util/unicorn: Use python2 and fixes

- dev-util/sonarqube-bin/files/sonar.init
The init file's stop() function didn't work and SonarQube continued to run in the background. This happens because the script that is launched, launches another wrapper that spawns SonarQube according to the system's arch (32/64 bit). I'm not sure how to solve this using a pidfile, and instead worked around it using `--name`. It's less elegant this way, I admit, but if anyone has a more elegant solution, please share.
Also, no logging was happening and I decided to remove this from the init file as well.
> fixing sonarqube's stop() function

- dev-python/maxminddb/maxminddb-1.4.1-r1.ebuild
Fixed dep in order to avoid the following message:
```
emerge: there are no ebuilds built with USE flags to satisfy "dev-python/ipaddress[python_targets_pypy(-)?,python_targets_pypy3(-)?,python_targets_python2_7(-)?,python_targets_python3_4(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,-python_single_target_pypy(-),-python_single_target_pypy3(-),-python_single_target_python2_7(-),-python_single_target_python3_4(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-)]".
!!! One of the following packages is required to complete your request:
- dev-python/maxminddb-1.4.1::pentoo (Change USE: -python_targets_python3_6)
(dependency required by "dev-python/maxminddb-1.4.1::pentoo" [ebuild])
(dependency required by "dev-python/maxminddb" [argument])
```
> fixing maxminddb dep for dirhunt

- profiles/pentoo/base/package.accept_keywords/dev-python
- profiles/pentoo/base/package.accept_keywords/net-analyzer
I think this was missing when recon-ng was bumped in baf98c48828d05ec2479fd61a7b7a01a51316f90
> profile: fixing recon-ng

- profiles/pentoo/base/package.accept_keywords/app-crypt
- profiles/pentoo/base/package.accept_keywords/dev-go
- profiles/pentoo/base/package.accept_keywords/dev-vcs
- profiles/pentoo/base/package.accept_keywords/net-analyzer
- profiles/pentoo/base/package.accept_keywords/net-wireless
I noticed some missing keywords for some packages I use (and probably other people as well). I usually just add those keywords to my own package.accept_keywords file but perhaps these should be added to the overlay instead, right?
> keywords: adding missing keywords

- sys-kernel/kconfig-hardened-check/kconfig-hardened-check-9999.ebuild
Upstream uses setuptools since https://github.com/a13xp0p0v/kconfig-hardened-check/commit/18c23c0e80ec6317566a282d29f8fc65ca262f54
> sys-kernel/kconfig-hardened-check: Convert ebuild to use distutils-r1.eclass

- net-analyzer/dirsearch/dirsearch-0.3.8-r1.ebuild
- net-analyzer/dirsearch/dirsearch-0.3.9.ebuild
net-analyzer/dirsearch depends on Python with the `threads` USE flag. This flag was dropped with Python 3.7 and later. Portage therefore fails to resolve the dependency and dirsearch can not be installed for Python 3.7+.
This PR fixes the USE flag dependency so dirsearch can be installed with with modern Python versions.
> net-analyzer/dirsearch: Fix dependency on python >= 3.7

- app-admin/genmenu/genmenu-9999.ebuild
Both app-admin/genmenu and net-wireless/fern-wifi-cracker create the
same symlink.
If genmenu is installed without fern-wifi-cracker present,
then there is a QA Notice symlink target does not exist.
Installing fern-wifi-cracker after genmenu fails due to file collision.
app-admin/genmenu:
Symlink was added in 2015 with ae660fbbd8751e04b761036eb610dcb1edf85877
net-wireless/fern-wifi-cracker
Symlink was added in 2019 with da69abbc3e29b7a8a2a5c03de607cd5db1f06c35
> genmenu: Remove symlink for fern-wifi-cracker

- scripts/pentoo-updater.sh
Option --disklabel was removed from genkernel:
https://github.com/gentoo/genkernel/commit/945b3dc65cb2577a9962db40848eaeae3fc2a425
Genkernel-4.1.2 became stable:
https://github.com/gentoo/gentoo/commit/89de8857672c0d7efb6a630b4075b6119527b893
Fixes: #672
> pentoo-updater: Remove genkernel option disklabel

- sys-devel/gef/gef-9999.ebuild
Since v2021.01 GEF doesn't ship with a Dockerfile.
Package-Manager: Portage-3.0.18, Repoman-3.0.3
Signed-off-by: Azat Bahawi <azahi@teknik.io>
> sys-devel/gef: Remove Dockerfile from installed docs

- app-crypt/haiti-hash/haiti-hash-1.0.1.ebuild
haiti 1.1.0 and 1.1.1 were released
- https://github.com/noraj/haiti/releases
- https://github.com/noraj/haiti/blob/master/docs/CHANGELOG.md
It now supports ruby 3.0 and a new file was added (`commons.json`)
> haiti: v1.1.1

- app-exploits/ropper/ropper-9999.ebuild
- sys-devel/gef/gef-9999.ebuild
Gentoo recently switched to using python 3.9 as the default, and these two packages were left behind on my system. I am sure there are others that need to be bumped, but this is what affected me.
This makes changes to `*-9999.ebuild` packages, which are symlinked to by actual versioned packages. I don't know what the policy is there but those packages may need to be incremented to have an `-r1` suffix.
> Bump two packages for the python 3.9 switch

- dev-util/unicorn/unicorn-1.0.3-r1.ebuild
unicorn-1.0.3 wasn't installing any of the headers or libraries. In fact, when the python USE flag was omitted, it wasn't installing any files at all.
The problem was a minor typo, which is fixed now.
> unicorn: fix files missing from install

- sys-devel/pwndbg/pwndbg-20210622.ebuild
https://github.com/pwndbg/pwndbg/releases/tag/2021.06.22
Seems to work. I didn't take the time to try and fix the missing `doc` and `test` USE flags, as indicated in the comments.
> pwndbg: 20210622 ebuild

- app-exploits/pwntools/pwntools-4.5.1-r1.ebuild
The current version of pwntools depends on a specific version of unicorn (see https://github.com/Gallopsled/pwntools/blob/5b0bec0c09c24f769a02b676500795db36dd40e0/setup.py#L63). It seems to work fine with the more recent unicorn, but according to issues on the pwntools and unicorn github (see the above link if interested), there is a bug related to MIPS support. So this just mimics pwntool's native `setup.py` by requiring a specific version of unicorn, which we already have in the pentoo tree anyway.
As with these diffs that involve new copies of files, it's hard to see a diff, but all I did was change line 35 to depend on that specific unicorn version, rather than pulling in just any version.
> pwntools: set unicorn dependency to proper version

- net-wireless/sdrangel/sdrangel-6.15.1.ebuild
Package was building with all required dependencies but DSD plugin was not enabled at compile time this should fix it
> sdrangel: fix DSD plugin

- net-wireless/sdrpp/sdrpp-1.0.4.ebuild
- net-wireless/sdrpp/sdrpp-9999.ebuild
`airspyhf`: enable support for AirspyHF devices (requires `net-wireless/airspyhf`)
Reference PR #751 for `net-wireless/airspyhf` drivers
> net-wireless/sdrpp: add support for airspyhf module

- dev-libs/nanopb/metadata.xml
- dev-libs/nanopb/nanopb-0.4.6-r1.ebuild
Modification required by net-wireless/qflipper
Signed-off-by: Thibaud CANALE <thican@thican.net>
> dev-libs/nanopb: Provides pb_release symbole

- dev-ruby/cms_scanner/cms_scanner-0.13.6.ebuild
- dev-ruby/cms_scanner/cms_scanner-0.13.7.ebuild
- dev-ruby/cms_scanner/cms_scanner-0.13.8.ebuild
Portage dropped the old ethon version so dependency resolution was broken. I synced this with upstream. This fixes dep resolution and might be enough to allow for building wpscan on ruby3.0/3.1 target.
Signed-off-by: Joe Kappus <joe@wt.gd>
> dev-ruby/cms_scanner: update dependencies

- dev-python/apng/apng-0.3.3.ebuild
- dev-python/apng/apng-0.3.4.ebuild
Not only is the backported module functionality not needed upstream, but moreover it is only used in tests with are deleted right away during prepare phase.  This fixes a non-existing dependency of for pathlib2 with newer python.
> dev-python/apng: Remove pathlib2 dependency

- net-misc/sherlock/sherlock-9999.ebuild
Adds dev-python/pandas as a dependency to the live ebuild.
> net-misc/sherlock: Add dependency to live ebuild

- README.md
layman has been deprecated by gentoo and eselect repository took it's place
> layman deprecation notice

- net-analyzer/wpscan/wpscan-3.8.25.ebuild
Upstream has bumped the dev-ruby/cms_scanner dependency to version 0.13.9: https://github.com/wpscanteam/wpscan/compare/v3.8.24...v3.8.25#diff-7563db6e4a74b7ffc1bfed662a343ca314eb8aa36fdd551154a09531d26b47c5R23
But the ebuild hasn't been updated accordingly.
Trying to build with an older version fails:
```
* Running prepare phase for all
* Running prepare phase for all
* Running source copy phase for ruby31
* Running prepare phase for ruby31
Resolving dependencies...
Could not find gem 'cms_scanner (~> 0.13.9)', which is required by gem 'wpscan', in any of the sources.
The source contains the following gems matching 'cms_scanner':
* cms_scanner-0.13.8
```
> net-analyzer/wpscan: Bump dev-ruby/cms_scanner dependency version.

- app-forensics/libewf/libewf-20230212.ebuild
ewfmount links to libfuse.so.2, which is provided by sys-fs/fuse:0 but not by sys-fs/fuse:3. Without specifying the slot, sys-fs/fuse:3 would satisfy the dependency without providing the required lib, resulting in a build with fuse support disabled.
> app-forensics/libewf: fix fuse dependency

- dev-python/cc2538-bsl/metadata.xml
- pentoo/pentoo-core/pentoo-core-2024.1-r2.ebuild
- pentoo/pentoo-proxies/pentoo-proxies-2024.1.ebuild
- pentoo/zero-system/zero-system-2024.1.ebuild
- profiles/pentoo/base/package.keywords/python3_12
- profiles/pentoo/base/package.mask
- profiles/pentoo/base/packages
- profiles/pentoo/zero-system/make.defaults
- profiles/pentoo/zero-system/use.mask
- zero-profile: make intent more clear
- cc2538-bsl: add missing metadata
- pentoo-core: drop elfix
- profile: drop elfix
- zero-system: drop vidcutter
- pentoo-proxies: drop mitmproxy, unmaintained in gentoo, tests fail, out of date
- profile: python 3.12 stuff
> python bump

- app-crypt/steghide/steghide-0.5.1-r1.ebuild
When /bin/sh is symlinked to the dash shell, app-crypt/steghide compiles just fine but fails at the installation phase with the following error:
```
[...]
/bin/sh libtool --tag=CXX   --mode=install /usr/lib/portage/python3.11/ebuild-helpers/xattr/install -c steghide '/var/tmp/portage/app-crypt/steghide-0.5.1-r1/image/usr/bin'
/bin/sh: 0: cannot open libtool: No such file
make[2]: *** [Makefile:439: install-binPROGRAMS] Error 2
[...]
```
This PR fixes it.
> fix steghide install when /bin/sh is dash

- dev-ruby/cms_scanner/cms_scanner-0.13.9.ebuild
dev-ruby/public_suffix:4 masked in gentoo to be dropped next month.
Relax to allow 5.0.5 as only 5.1.0 and later blocked
See-also: https://github.com/wpscanteam/CMSScanner/blob/v0.13.9/cms_scanner.gemspec
> dev-ruby/cms_scanner: 0.13.9 relax publix_suffix dep

- profiles/pentoo/hardened/linux/amd64/23.0/split-usr/parent
profile: fix missing split-usr
> profile: fix missing split-usr

- profiles/pentoo/base/make.defaults
catalyst was overriding these but the profile is setting them the old
way instead of the new way.  This should affect almost no systems but
new catalyst doesn't seem to be overriding this
> update some dir locations

- profiles/pentoo/bootstrap/package.use
I removed zstd from libarchive to avoid a loop but it is required so
I'll have to find a different way.
> bootstrap-profile: looks like zstd is required now

- dev-libs/openssl-bad/openssl-bad-1.0.2_p20220901-r1.ebuild
- net-analyzer/testssl/testssl-3.0.8.ebuild
- net-analyzer/testssl/testssl-3.0.9.ebuild
- net-analyzer/testssl/testssl-3.2_rc3.ebuild
- pentoo/zero-system/files/TODO
- pentoo/zero-system/files/zshrc
- pentoo/zero-system/zero-system-2024.3.ebuild
- profiles/pentoo/base/package.use.force
- **openssl-bad doesn't build anymore, so no more keywords**
- **testssl: force bundled**
- **zero-system: some cleanup**
- **add a note for me**
- **improve note**
> openssl bad

- profiles/pentoo/base/package.mask
- profiles/pentoo/bootstrap/package.use
- scripts/pentoo-updater.sh
- **bootstrap-profile: less quic again**
- **pentoo-updater: java and ruby updates**
- **package.mask: xfce4-screensaver isn't broken, pam was**
> branchy mcbranchface

- net-proxy/zaproxy/zaproxy-2.14.0.ebuild
- net-proxy/zaproxy/zaproxy-2.15.0.ebuild
net-proxy/zaproxy was failing to install on my [Gentoo Prefix](https://wiki.gentoo.org/wiki/Project:Prefix) system. Fixed it by using the ebuild install functions instead of cp.
Also removed the explicit $EPREFIX from the dosym, since it was breaking the link on prefix systems because dosym already takes care of that stuff.
Additionally I noticed some (apparently harmless) errors on setup: a glob that wouldn't expand because it was quoted (fixed on second commit) and a reference to a variable $PLUGIN_HUD that was never assigned a value, resulting in a failed attempt to copy the $DISTDIR directory on line 87 since it evaluates to nothing. I did not touch the latter because I honestly do not fully understand the point of the whole deleting and copying back from another source thing, but I …
> fixes for zaproxy

- dev-util/ghidra/ghidra-11.1.2.ebuild
- dev-util/ghidra/ghidra-11.2.1.ebuild
- dev-util/ghidra/ghidra-11.2.ebuild
Build ghidra currently is broken. Emerge cannot download hfsexplorer-0_21-bin.zip from old source.
> ghidra: fix src url

- pentoo/pentoo-proxies/pentoo-proxies-2025.0.ebuild
- pentoo/pentoo-scanner/pentoo-scanner-2025.0.ebuild
- **pentoo-proxies: drop tsocks https://bugs.gentoo.org/920323**
- **pentoo-scanner: drop ike-scan, fails to build**
> drop failures

- net-misc/linkfinder/linkfinder-20191124.ebuild
Fixes #2286
Use distutils-r1_src_install instead of distutils-r1_python_install.
distutils-r1_src_isntall invokes distutils-r1_python_install inside distutils-r1_foreach_impl.
> linkfinder: Fix #2286

- net-mail/fakepop/fakepop-11.ebuild
- net-mail/fakepop/metadata.xml
#1823 has already been solved, but I update the homepage and add metadata with upstream URL. I've also updated the copyright date for 2025. I think we can closed that issue
> fix old link and add metadata

- dev-python/pydub/pydub-0.25.1.ebuild
the patch can be removed when a new version with [this PR](https://github.com/jiaaro/pydub/pull/744) or [this PR](https://github.com/jiaaro/pydub/pull/769) will be out.
I've tested the ebuild with `ebuild pydub-0.25.1.ebuild clean test`, it works without the python_test function (113 tests passed).
The issue #1751 can be closed
> pydub: fix test

- pentoo/pentoo-core/pentoo-core-2025.2.ebuild
we don't use it right now, and it's failing to build in docker for some
reason
> pentoo-core: remove mirrorselect

- net-analyzer/responder/responder-3.1.6.0-r1.ebuild
Responder needs the aioquic and netifaces packages to run, but these are not listed in the ebuild, which leads to a failure when trying to run it. The new ebuild is the one I am using locally to resolve this. While both dependencies are available in the main Gentoo repository, aioquic does not have an x86 keyword, so it is missing in this ebuild as well.
> net-analyzer/responder: needs aioquic and netifaces

- dev-python/pylzma/pylzma-0.5.0.ebuild
I've opened a PR on the repository, to fix my dirty patches : https://github.com/fancycode/pylzma/pull/86
I've compiled and executed the tests, they all passed. I didn't take the time to check deeper if everything is alright.
I've also compiled and executed the tests on Python 3.13, it works. The issue linked (https://github.com/fancycode/pylzma/issues/80) wasn't about Python 3.13, and people have tested it on Fedora (https://github.com/bkerler/edl/issues/615#issuecomment-2587899415).
It closes issues #1180 and #1435.
> pylzma: fix tests and compilation
