pentoo/pentoo-overlay

profiles/pentoo/base/package.accept_keywords/net-firewall
[ebuild replace] replace sanewall with firehol-2.0.3 #5
=> replace sanewall with firehol

dev-python/acora/acora-9999.ebuild, dev-python/dotty/dotty-9999.ebuild, dev-python/intervaltree/intervaltree-9999.ebuild, dev-python/pyaff4/pyaff4-9999.ebuild, dev-python/sortedcontainers/sortedcontainers-9999.ebuild
install_requires : pyaff4, acora, sortedcontainers, interaltree, dotty ebuilds
=> rekall: install requires

net-analyzer/bonesi/bonesi-9999.ebuild
BoNeSi DDoS Botnet Simulator https://github.com/pentoo/pentoo-overlay/issues/36
=> [ebuild request] add "BoNeSi" DDoS Botnet Simulator

net-analyzer/nikto/nikto-2.1.5-r2.ebuild
Reverts pentoo/pentoo-overlay#47
=> Revert "net-analyzer/nikto: fix config file could not find error."

net-wireless/n4p/n4p-2.2-r1.ebuild, pentoo/pentoo-misc/pentoo-misc-2017.0.ebuild, pentoo/tribe/tribe-2012.0.ebuild, profiles/pentoo/arch/arm/package.accept_keywords/proxies, profiles/pentoo/base/package.accept_keywords/net-misc, profiles/pentoo/base/package.use/net-misc
Fixes https://github.com/pentoo/pentoo-overlay/issues/174
Now works emerge world.
Cya.
=> fix moved packages from portage tree

net-proxy/mitmproxy/mitmproxy-2.0.2-r6.ebuild, net-proxy/mitmproxy/mitmproxy-9999.ebuild
This change makes USE=doc work.
=> mitmproxy: fix documentation generation

net-wireless/cubicsdr/cubicsdr-0.2.3.ebuild
* adds dependency for wxGTK opengl USE
* adds USE flags and dependencies for alsa and pulseaudio
=> improve the CubicSDR ebuild

pentoo/pentoo-installer/pentoo-installer-99999999.ebuild
app-misc/jq: read/write json config-files
sys-fs/growpart: auto-grow partitions
See pentoo/pentoo-installer#45
=> pentoo/pentoo-installer: Add PDEPEND

profiles/pentoo/base/package.accept_keywords/dev-python
Forgot to add keywords to properly update to new dirhunt version. :-)
=> adding dirhunt deps keywords

net-vpn/udp2raw-tunnel/files/udp2raw-daemon.confd, net-vpn/udp2raw-tunnel/files/udp2raw-daemon.initd, net-vpn/udp2raw-tunnel/metadata.xml, net-vpn/udp2raw-tunnel/udp2raw-tunnel-20181113.0.ebuild, net-vpn/udp2raw-tunnel/udp2raw-tunnel-99999999.ebuild
=> udp2raw-tunnel: new tool

dev-util/ghidra/ghidra-9.0.2-r1.ebuild
Add missing || die 
remove dead code
add variable ${PN}
=> dev-util/ghidra: ebuild cleanup

dev-libs/libcerror/libcerror-20201121.ebuild, dev-libs/libcerror/libcerror-20220101.ebuild
=> removal of .la files from libcerror

net-wireless/gps-sdr-sim/gps-sdr-sim-9999.ebuild
commit 654a9888c54218766909e15fe8139e4bc8e83ecc
=> net-wireless/gps-sdr-sim :: update after new commit

net-wireless/srsran/srsran-22.10.ebuild
=> net-wireless/srsran :: new version

app-fuzz/smtp-fuzz/smtp-fuzz-0.1.ebuild
updated ebuild to emerge cleanly with no errors
=>  app-fuzz/smtp-fuzz :: ebuild update

app-fuzz/http-fuzz/http-fuzz-0.1.ebuild
updated ebuild to emerge cleanly with no errors
=>  app-fuzz/http-fuzz :: ebuild update

net-misc/voipong/voipong-2.0.ebuild
updated ebuild to emerge cleanly with no errors from git
=> net-misc/voipong :: ebuild update

dev-python/agate/agate-1.6.1-r1.ebuild, dev-python/asyncpg/asyncpg-0.23.0.ebuild, dev-python/asyncpg/asyncpg-0.27.0.ebuild, dev-python/graphql-core/graphql-core-3.1.5.ebuild, sci-electronics/migen/migen-0.7.ebuild
See gentoo commit https://github.com/gentoo/gentoo/commit/15d76ea3e49bf90f74df649773167d6ba96c0583
=> dev-python/*: Rename dev-python/{sphinx_rtd_theme → sphinx-rtd-theme}

net-wireless/mousejack/files/mousejack, net-wireless/mousejack/metadata.xml, net-wireless/mousejack/mousejack-9999.ebuild, net-wireless/rfcat/rfcat-2.0.1-r1.ebuild, profiles/pentoo/zero-system/make.defaults, profiles/pentoo/zero-system/package.use/sys-apps, scripts/git_local_prune
- rfcat: fix for python 3.12
- rfcat: add comment about future bug
=> python3 12 testing

sci-electronics/rd-usb/rd-usb-1.22.1.ebuild
=> rd-usb: cleanup

dev-util/ghidra/ghidra-11.1.ebuild
=> ghidra: deps fix

net-analyzer/honeypots/honeypots-0.65-r1.ebuild
=> requires psycopg2

.github/workflows/pkgcheck.yaml, .github/workflows/pkgcheck_merge.yaml, dev-java/jd-lib/metadata.xml
- fix metadata.xml
- tigher checks to avoid this failure in the future
=> odd failure

profiles/pentoo/zero-system/package.use/catalyst, profiles/pentoo/zero-system/use.mask
- catalyst: cleanup
- zero-profile: use catalyst on 3.11 for now
=> catalyst updates

dev-python/py-pdf-parser/py-pdf-parser-0.12.0.ebuild
=> py-pdf-parser: cleanup

net-analyzer/gobuster/gobuster-3.6.0.ebuild
=> gobuster: typo fix

profiles/pentoo/base/package.use/dev-qt, scripts/pentoo-updater.sh
- **pentoo-updater: fix missing newline**
- **profile: add needed use flag for qt stuff and sort file**
=> updates zero

dev-util/ghidra/ghidra-11.1.1.ebuild
ghidra: fix https://github.com/pentoo/pentoo-overlay/issues/1984
=> ghidra: fix https://github.com/pentoo/pentoo-overlay/issues/1984

app-pda/libplist/files/libplist-2.6.0-makefile.patch, app-pda/libplist/libplist-2.6.0-r1.ebuild
fix https://github.com/pentoo/pentoo-overlay/issues/1991
=> fix https://github.com/pentoo/pentoo-overlay/issues/1991

dev-python/biplist/biplist-1.0.3.ebuild, dev-python/biplist/metadata.xml
=> biplist: pkgcheck

dev-python/biplist/biplist-1.0.3.ebuild
=> biplist: minor

dev-python/python-libnmap/python-libnmap-0.7.3-r1.ebuild
=> python-libnmap

dev-python/xlutils/xlutils-2.0.0-r1.ebuild
=> xlutils: pkgcheck fix

pentoo/pentoo-misc/pentoo-misc-2024.2.ebuild
=> pentoo-misc: remove jitsi

profiles/pentoo/base/package.accept_keywords/dev-ruby
=> ruby keywords

pentoo/zero-system/zero-system-2024.2-r2.ebuild, profiles/pentoo/base/package.use.stable.mask, profiles/pentoo/overlay/package.use.stable.mask, scripts/pentoo-updater.sh
- **profile: remove lto mask on chromium**
- **media-tv/libv4l->media-libs/libv4l**
=> more updates

profiles/pentoo/base/package.use.mask, profiles/pentoo/base/package.use/dev-lang, profiles/pentoo/base/package.use/dev-libs
- **match all the rust[profile] stuff**
- **profile: update pocl use flags**
=> updates again

profiles/pentoo/base/package.accept_keywords/dev-db
=> profile: keywords

app-forensics/bulk_extractor/bulk_extractor-2.1.0.ebuild
=> bulk_extractor

profiles/pentoo/base/package.accept_keywords/dev-libs
=> protobuf-27.2

profiles/pentoo/bootstrap/package.use, profiles/pentoo/zero-system/profile.bashrc
- **zero-profile: more exceptions**
- **bootstrap: less curl deps**
=> bootstrap etc

net-analyzer/snmpenum/snmpenum-1.0-r1.ebuild, profiles/pentoo/bootstrap/package.use
- **bootstrap-profile: fix curl better**
- **snmpenum: mirror the files**
=> snmpenum mirror

app-exploits/packetstormexploits-meta/packetstormexploits-meta-2022.ebuild, app-exploits/packetstormexploits-meta/packetstormexploits-meta-2023.ebuild
=> packetstormexploits-meta

dev-python/sslpsk-pmd3/sslpsk-pmd3-1.0.3.ebuild
=> sslpsk-pmd3

pentoo/pentoo-radio/pentoo-radio-2024.1-r2.ebuild
=> pentoo-radio

profiles/pentoo/base/package.accept_keywords/dev-python, profiles/pentoo/zero-system/profile.bashrc
- **profile: terminaltables3**
- **zero-profile: relax**
=> todays fixes

dev-util/ghidra/ghidra-11.3.1-r1.ebuild, profiles/pentoo/zero-system/profile.bashrc
- **ghidra: add missing || die and fidb files**
- **zero-profile: more relaxing**
=> more ghidra

pentoo/pentoo-desktop/pentoo-desktop-2025.2.ebuild
=> pentoo-desktop

dev-python/python-oauth2/python-oauth2-1.1.1-r1.ebuild
=> python-oauth2

sys-kernel/pentoo-sources/files/4005_kali-wifi-injection-without-4004.patch, sys-kernel/pentoo-sources/pentoo-sources-6.12.9.ebuild
=> pentoo-sources

pentoo/pentoo-radio/pentoo-radio-2025.1.ebuild, profiles/pentoo/base/make.defaults
- **pentoo-radio: drop editcp, needs dead qt5**
- **profile: update python safely**
=> 20250427r1

www-apps/BloodHound/BloodHound-4.3.1.ebuild
=> BloodHound

dev-python/censys/censys-2.2.17.ebuild, dev-python/config/config-0.5.1.ebuild, dev-python/django-guardian/django-guardian-2.4.0.ebuild, dev-python/django-guardian/django-guardian-3.0.1.ebuild, dev-python/dropbox-sdk/dropbox-sdk-12.0.2.ebuild, dev-python/htmlentities/htmlentities-0.3.0.ebuild, dev-python/promise/promise-2.3.0.ebuild, dev-python/proxy-db/proxy-db-0.3.1.ebuild, dev-python/proxy-db/proxy-db-9999.ebuild
=> dev-python: fix htmlentites and best practice with use=test

net-wireless/LTESniffer/LTESniffer-2.1.0.ebuild, net-wireless/LTESniffer/files/cmake/modules/FindSRSRAN.cmake, net-wireless/srsran2/srsran2-20231020.ebuild, net-wireless/srsran2/srsran2-20240929.ebuild
=> LTESniffer

net-analyzer/metasploit/metasploit-9999.ebuild
=> metasploit

pentoo/pentoo-misc/pentoo-misc-2025.2.ebuild
=> pentoo-misc
